package com.manageappsdk

import android.app.Application
import android.content.Context
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.view.View
import android.view.ViewGroup
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.JSBundleLoader
import com.facebook.react.common.annotations.UnstableReactNativeAPI
import com.facebook.react.defaults.DefaultComponentsRegistry
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import com.facebook.react.defaults.DefaultReactHostDelegate
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.react.defaults.DefaultTurboModuleManagerDelegate
import com.facebook.react.fabric.ComponentFactory
import com.facebook.react.runtime.JSCInstance
import com.facebook.react.runtime.ReactHostImpl
import com.facebook.react.runtime.hermes.HermesInstance

class ManageAppSDKActivity : ReactActivity() {

    companion object {
        @Volatile private var _sdkHost: ReactNativeHost? = null
        @Volatile private var _sdkReactHost: ReactHost? = null
        private val sdkHostLock = Any()
        @Volatile var isResetting = false

        /**
         * Build the package list for the SDK's isolated React instance.
         *
         * The SDK bundle uses native modules (netinfo, async-storage, reanimated, etc.)
         * that are autolinked into the host app. We get them by instantiating the host
         * app's generated PackageList via reflection, then appending our own package.
         *
         * Falls back to just ManageAppSDKPackage if PackageList can't be found
         * (e.g. during unit tests or unusual build setups).
         */
        private fun buildPackageList(host: ReactNativeHost): List<ReactPackage> {
            return try {
                // PackageList is generated by RN's Gradle plugin into the host app's
                // package (e.g. com.yourapp.PackageList). We find it via reflection.
                val packageListClass = Class.forName("com.facebook.react.PackageList")
                val constructor = packageListClass.getConstructor(ReactNativeHost::class.java)
                val packageList = constructor.newInstance(host)
                val packagesMethod = packageListClass.getMethod("getPackages")
                @Suppress("UNCHECKED_CAST")
                val packages = packagesMethod.invoke(packageList) as MutableList<ReactPackage>
                // Add our own package on top
                packages.add(ManageAppSDKPackage())
                packages
            } catch (e: Exception) {
                Log.w("SDK_DEBUG", "Could not load PackageList via reflection, using minimal packages: ${e.message}")
                listOf(ManageAppSDKPackage())
            }
        }

        fun getSdkHost(context: Context): ReactNativeHost =
            _sdkHost ?: synchronized(sdkHostLock) {
                _sdkHost ?: createSdkHost(context).also {
                    _sdkHost = it
                    _sdkReactHost = createSdkReactHost(context, it)
                    Log.d("SDK_DEBUG", "SDK host + reactHost created")
                }
            }

        fun getSdkReactHost(context: Context): ReactHost =
            getSdkHost(context).let { _sdkReactHost!! }

        /**
         * Calls CodePush.getJSBundleFile() via reflection — zero compile-time
         * dependency on @revopush/react-native-code-push.
         * Returns null if CodePush is not present, falling back to bundled assets.
         */
        private fun getBundlePath(): String? {
            return try {
                val codePushClass = Class.forName("com.microsoft.codepush.react.CodePush")
                val method = codePushClass.getMethod("getJSBundleFile", String::class.java)
                method.invoke(null, BUNDLE_NAME) as? String
            } catch (e: ClassNotFoundException) {
                Log.i("SDK_DEBUG", "CodePush not present — using bundled assets")
                null
            } catch (e: Exception) {
                Log.w("SDK_DEBUG", "CodePush call failed — using bundled assets: ${e.message}")
                null
            }
        }

        private fun createSdkHost(context: Context): ReactNativeHost {
            val host = object : DefaultReactNativeHost(context.applicationContext as Application) {
                override fun getPackages(): List<ReactPackage> = buildPackageList(this)
                override fun getJSBundleFile(): String? = getBundlePath()
                override fun getBundleAssetName(): String = BUNDLE_NAME
                override fun getJSMainModuleName(): String = "index"
                // ALWAYS false — the SDK must never connect to Metro dev server,
                // regardless of whether the host app is a debug build.
                override fun getUseDeveloperSupport(): Boolean = false
                override val isNewArchEnabled: Boolean get() = isNewArchitectureEnabled(context)
                override val isHermesEnabled: Boolean get() = isHermesEnabled(context)
            }
            return host
        }

        @OptIn(UnstableReactNativeAPI::class)
        private fun createSdkReactHost(context: Context, sdkHost: ReactNativeHost): ReactHost {
            val codepushPath = getBundlePath()
            Log.d("SDK_DEBUG_PATH", "$codepushPath")

            val bundleLoader: JSBundleLoader =
                if (codepushPath == null || codepushPath.startsWith("assets://"))
                    JSBundleLoader.createAssetLoader(
                        context.applicationContext,
                        codepushPath ?: "assets://$BUNDLE_NAME",
                        true
                    )
                else
                    JSBundleLoader.createFileLoader(codepushPath)

            val delegate = DefaultReactHostDelegate(
                jsMainModulePath = "index",
                jsBundleLoader = bundleLoader,
                reactPackages = buildPackageList(sdkHost),
                jsRuntimeFactory = if (isHermesEnabled(context)) HermesInstance() else JSCInstance(),
                turboModuleManagerDelegateBuilder = DefaultTurboModuleManagerDelegate.Builder()
            )

            val componentFactory = ComponentFactory()
            DefaultComponentsRegistry.register(componentFactory)

            return ReactHostImpl(
                context.applicationContext,
                delegate,
                componentFactory,
                true,
                false
            )
        }

        fun preloadSDKInstance(context: Context) {
            Thread {
                try {
                    val host = getSdkHost(context)
                    Handler(Looper.getMainLooper()).post {
                        try {
                            if (isNewArchitectureEnabled(context)) {
                                _sdkReactHost?.start()
                                Log.d("SDK_DEBUG", "SDK ReactHost.start() called (New Arch)")
                            } else if (!host.reactInstanceManager.hasStartedCreatingInitialContext()) {
                                host.reactInstanceManager.createReactContextInBackground()
                                Log.d("SDK_DEBUG", "SDK context preload started (Old Arch)")
                            } else {
                                Log.d("SDK_DEBUG", "SDK context already warming/warm")
                            }
                        } catch (e: Exception) {
                            Log.e("SDK_DEBUG", "Preload post to main thread failed: ${e.message}")
                        }
                    }
                } catch (e: Exception) {
                    Log.e("SDK_DEBUG", "SDK host creation failed during preload: ${e.message}")
                }
            }.start()
        }

        fun resetSDKInstance(context: Context) {
            Handler(Looper.getMainLooper()).post {
                synchronized(sdkHostLock) {
                    try {
                        if (isNewArchitectureEnabled(context)) {
                            _sdkReactHost?.destroy("Resetting SDK Instance", null)
                            Log.d("SDK_DEBUG", "SDK ReactHost destroyed (New Arch)")
                            _sdkHost = null
                            _sdkReactHost = null
                        } else {
                            _sdkHost?.reactInstanceManager?.let {
                                it.onHostDestroy()
                                it.destroy()
                            }
                            Log.d("SDK_DEBUG", "SDK InstanceManager destroyed (Old Arch)")
                            _sdkHost = null
                            _sdkReactHost = null
                        }
                    } catch (e: Exception) {
                        Log.e("SDK_DEBUG", "Reset failed: ${e.message}")
                    }
                }

                // if (!isNewArchitectureEnabled(context))
                    Handler(Looper.getMainLooper()).postDelayed({
                        isResetting = false
                        preloadSDKInstance(context)
                    }, 500)
                // else
                //     isResetting = false
            }
        }

        // ---------------------------------------------------------------------------
        // Read arch/hermes flags from the host app's BuildConfig at runtime via
        // reflection — a library module cannot reference the app's BuildConfig directly.
        // ---------------------------------------------------------------------------
        private fun isNewArchitectureEnabled(context: Context): Boolean {
            return try {
                val cls = Class.forName("${context.packageName}.BuildConfig")
                cls.getField("IS_NEW_ARCHITECTURE_ENABLED").getBoolean(null)
            } catch (e: Exception) {
                false
            }
        }

        private fun isHermesEnabled(context: Context): Boolean {
            return try {
                val cls = Class.forName("${context.packageName}.BuildConfig")
                cls.getField("IS_HERMES_ENABLED").getBoolean(null)
            } catch (e: Exception) {
                true
            }
        }

        private const val BUNDLE_NAME = "sdk.android.bundle"
    }

    override fun getMainComponentName(): String = "ManageAppSDK"

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(androidx.appcompat.R.style.Theme_AppCompat_Light_NoActionBar)
        val splashMask = buildSplashMask()
        (window.decorView as? ViewGroup)?.addView(splashMask)
        ensureSDKHostReady()
        super.onCreate(savedInstanceState)
        splashMask.postDelayed({
            splashMask.animate().alpha(0f).setDuration(400)
                .withEndAction {
                    (splashMask.parent as? ViewGroup)?.removeView(splashMask)
                }.start()
        }, 500)
    }

    private fun ensureSDKHostReady() {
        try {
            if (isNewArchitectureEnabled(applicationContext)) {
                getSdkReactHost(applicationContext).start()
                Log.d("SDK_DEBUG", "ReactHost.start() called on launch (New Arch)")
            } else {
                val host = getSdkHost(applicationContext)
                if (!host.reactInstanceManager.hasStartedCreatingInitialContext()) {
                    Log.d("SDK_DEBUG", "Host cold on launch — starting context now")
                    host.reactInstanceManager.createReactContextInBackground()
                } else {
                    Log.d("SDK_DEBUG", "Host already warm — fast launch")
                }
            }
        } catch (e: Exception) {
            Log.e("SDK_DEBUG", "ensureSDKHostReady failed: ${e.message}")
        }
    }

    private fun buildSplashMask(): View = View(this).apply {
        background = android.graphics.drawable.GradientDrawable(
            android.graphics.drawable.GradientDrawable.Orientation.TOP_BOTTOM,
            intArrayOf(0xFF340368.toInt(), 0xFF140128.toInt())
        )
        layoutParams = ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT
        )
    }

    override fun createReactActivityDelegate(): ReactActivityDelegate =
        object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {
            override fun getReactNativeHost(): ReactNativeHost = getSdkHost(applicationContext)
            override fun getReactHost(): ReactHost = getSdkReactHost(applicationContext)
            override fun getLaunchOptions(): Bundle = Bundle().also { props ->
                intent?.extras?.let { bundle ->
                    for (key in bundle.keySet()) {
                        when (val v = bundle.get(key)) {
                            is String  -> props.putString(key, v)
                            is Boolean -> props.putBoolean(key, v)
                            is Double  -> props.putDouble(key, v)
                            is Int     -> props.putInt(key, v)
                        }
                        Log.d("ManageAppSDK", "Prop -> $key: ${bundle.get(key)}")
                    }
                }
            }
        }

    override fun onPause() {
        isResetting = true
        super.onPause()
    }

    override fun onDestroy() {
        try {
            reactDelegate?.onHostDestroy()
        } catch (e: Exception) {
            Log.e("SDK_DEBUG", "delegate onHostDestroy failed: ${e.message}")
        }
        super.onDestroy()
        resetSDKInstance(applicationContext)
    }
}
